export const CHANGE_THEME = "CHANGE_THEME"

//tweet
export const TWEET_REQUEST = "TWEET_REQUEST"
export const TWEET_SUCCESS = "TWEET_SUCCESS"
export const TWEET_FAIL = "TWEET_FAIL"


//filters
export const CHANGE_RADIUS = "CHANGE_RADIUS"
export const CHANGE_POSITION = "CHANGE_POSITION"
export const CHANGE_NEW_SEARCH = "CHANGE_NEW_SEARCH"
export const CHANGE_SELECTION_RANGE = "CHANGE_SELECTION_RANGE"
export const CHANGE_POPULAR = "CHANGE_POPULAR"
export const CHANGE_ONLY_ITALIAN = "CHANGE_ONLY_ITALIAN"

